AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "DevOps infrastructure\n"
Parameters:
  ResourcePrefix:
    Type: String
  HostedZoneId:
    Type: String
  KeyNameJenkins:
    Type: String
  NameAmiJenkins:
    Type: String
    Default: ami-03f38e546e3dc59e1
  InstanceTypeJenkins:
    Type: String
    Default: t2.medium
  KeyNameSonarQube:
    Type: String
  NameAmiSonarQube:
    Type: String
    Default: ami-03f38e546e3dc59e1
  InstanceTypeSonarQube:
    Type: String
    Default: t2.medium
  CidrBlock:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 172.17.0.0/16
  BucketOriginBaseDomainName:
    Type: String
    Default: heztrada.com
  AcmCertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-1:337928833886:certificate/5018ed67-eee7-499d-ab1f-f82218626838
Resources:
  NestedStackWeb:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./web.yaml
      Parameters:
        ResourcePrefix:
          Ref: ResourcePrefix
        BucketOriginBaseDomainName:
          Ref: BucketOriginBaseDomainName
        AcmCertificateArn:
          Ref: AcmCertificateArn
  NestedStackVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml
      Parameters:
        ResourcePrefix:
          Ref: ResourcePrefix
        CidrBlock:
          Ref: CidrBlock
  NestedStackEc2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ec2.yaml
      Parameters:
        ResourcePrefix:
          Ref: ResourcePrefix
        KeyNameJenkins:
          Ref: KeyNameJenkins
        NameAmiJenkins:
          Ref: NameAmiJenkins
        InstanceTypeJenkins:
          Ref: InstanceTypeJenkins
        KeyNameSonarQube:
          Ref: KeyNameSonarQube
        NameAmiSonarQube:
          Ref: NameAmiSonarQube
        InstanceTypeSonarQube:
          Ref: InstanceTypeSonarQube
        PublicSubNet1:
          Fn::Sub: '{{resolve:ssm:/${ResourcePrefix}/vpc/subnet/public/list/0}}'
        Vpc:
          Fn::Sub: '{{resolve:ssm:/${ResourcePrefix}/vpc}}'
        HostedZoneId:
          Ref: HostedZoneId
